# Numpy Practice

In [2]:
import numpy as np

In [3]:
a = np.array([20,30,40])
b = np.array([60,70,80])
print('a =',a)
print()
print('b =',b)
print()
print('a + b =',a+b)
print()
print('a * b =',a*b)
print()
print('b - a =',b-a)
print()
print('b / a =',b/a)

a = [20 30 40]

b = [60 70 80]

a + b = [ 80 100 120]

a * b = [1200 2100 3200]

b - a = [40 40 40]

b / a = [3.         2.33333333 2.        ]


In [4]:
c = np.array([40,50,'60'])
print(c)

['40' '50' '60']


In [5]:
l1 = [20,30,40]
l2 = 5
print(l1*l2)

[20, 30, 40, 20, 30, 40, 20, 30, 40, 20, 30, 40, 20, 30, 40]


In [6]:
l3 = [[20,30],[40,50,60]]
print(l3)

[[20, 30], [40, 50, 60]]


In [7]:
l4 = np.array([[20,30,40],[50,60,70]])
print(l4)

[[20 30 40]
 [50 60 70]]


In [8]:
print(type(l4))

<class 'numpy.ndarray'>


In [9]:
l5 = np.array([20,30,40,50])
print(l5[0:3])
print()
print(l5[3:])
print()
print(l5[:])

[20 30 40]

[50]

[20 30 40 50]


In [10]:
l6 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(l6[1,1:3])
print(np.shape(l6))
print(np.size(l6))
print(np.ndim(l6))
print(l6.dtype)

[6 7]
(3, 4)
12
2
int64


In [11]:
ar = [30,40,50,60,70]
arr = np.array(ar)
print(arr) 
print()
print(arr.shape)        # rows,cols
print()
print(len(arr))         # no. of nested values
print()
print(np.size(arr))     # no. of elements
print()
print(type(arr))        # datatype of variable
print()
print(arr.dtype)        # datatype of array
print()
print(arr.astype(str))  # datatype conversion

[30 40 50 60 70]

(5,)

5

5

<class 'numpy.ndarray'>

int64

['30' '40' '50' '60' '70']


In [12]:
arr1= np.array([[30,40,50],[10,20,30]])
arr2 = np.array([[60,70,80],[30,40,50]])
print(arr1 + arr2)      # using operator
print()
print(np.add(arr1,arr2))    # using numpy

[[ 90 110 130]
 [ 40  60  80]]

[[ 90 110 130]
 [ 40  60  80]]


In [13]:
print(arr2 - arr1)      # using operator
print()
print(np.subtract(arr2,arr1))    # using numpy

[[30 30 30]
 [20 20 20]]

[[30 30 30]
 [20 20 20]]


In [14]:
print(arr1 * arr2)      # using operator
print()
print(np.multiply(arr1,arr2))    # using numpy

[[1800 2800 4000]
 [ 300  800 1500]]

[[1800 2800 4000]
 [ 300  800 1500]]


In [15]:
print(arr1 / arr2)      # using operator
print()
print(np.divide(arr1,arr2))    # using numpy

[[0.5        0.57142857 0.625     ]
 [0.33333333 0.5        0.6       ]]

[[0.5        0.57142857 0.625     ]
 [0.33333333 0.5        0.6       ]]


In [16]:
arr1= np.array([3,4,2,1])
arr3 = np.array([2])
print(np.power(arr1,arr3))    # using numpy

[ 9 16  4  1]


In [17]:
arr4 = np.array([9,16,4,1])
print(np.sqrt(arr4))

[3. 4. 2. 1.]


In [18]:
a = [30,40,50]
b = [20,30,40]
print(a+b)

[30, 40, 50, 20, 30, 40]


In [19]:
# Concatenation
arr1 = np.array([30,40,50])
arr2 = np.array([5,6,7])
print(np.concatenate([arr1,arr2]))

[30 40 50  5  6  7]


In [20]:
arr1 = np.array([[30,40],[50,30]])
arr2 = np.array([[5,5],[6,7]])
print(np.concatenate([arr1,arr2],axis = 1))

[[30 40  5  5]
 [50 30  6  7]]


In [21]:
print(np.concatenate([arr1,arr2],axis = 0))

[[30 40]
 [50 30]
 [ 5  5]
 [ 6  7]]


In [22]:
print(np.hstack([arr1,arr2]))     # horizontal concatenation

[[30 40  5  5]
 [50 30  6  7]]


In [23]:
print(np.vstack([arr1,arr2]))     # vertical concatenation

[[30 40]
 [50 30]
 [ 5  5]
 [ 6  7]]


In [24]:
a = np.array([20,30,40,50,60,70])
b = np.array_split(a,3)
print(b[2])

[60 70]


In [25]:
a = np.array([[20,30],[40,50]])
print(np.append(a,[60,70]))

[20 30 40 50 60 70]


In [26]:
print(np.insert(a,[1,2],[50,20],axis=1))

[[20 50 30 20]
 [40 50 50 20]]


In [27]:
print(a)
print()
print(np.delete(a,1,axis = 1))

[[20 30]
 [40 50]]

[[20]
 [40]]


In [28]:
b = np.array([7,8,3,6,2,4])
print(np.sort(b))

[2 3 4 6 7 8]


In [29]:
s = np.where(b == 4)
print(s)
ss = np.searchsorted(b,4)
print(ss)

(array([5]),)
0


In [30]:
ar = np.array([20,30,40,50])
fa = [True,False,True,False]

new = ar[fa]
print(new)

[20 40]


In [31]:
fa = ar>35
new = ar[fa]
print(new)

[40 50]


In [34]:
fa = ar%5==0
new = ar[fa]
print(new)

[20 30 40 50]


In [39]:
a = np.array([20,40,60,70])
print(np.sum(a))
print(np.min(a))
print(np.max(a))
print(np.size(a))
print(np.mean(a))
print(np.cumsum(a))
print(np.cumprod(a))

190
20
70
4
47.5
[ 20  60 120 190]
[     20     800   48000 3360000]


In [47]:
a = [100,150,199,200,250,130]
b = [10,50,30,40,30,10]

price = np.array(a)
quantity = np.array(b)

print(price,"\n",quantity)
print()
c = np.cumprod([price,quantity],axis=0)
print(c)

print()
print(c[1].sum())

[100 150 199 200 250 130] 
 [10 50 30 40 30 10]

[[ 100  150  199  200  250  130]
 [1000 7500 5970 8000 7500 1300]]

31270


In [48]:
baked_food = [200,300,150,130,200,280,170,188]

a = np.array(baked_food)
print(np.mean(baked_food))
print(np.median(baked_food))

202.25
194.0


In [52]:
import statistics as stats

print(stats.mode(baked_food))
print(np.std(baked_food))
print(np.var(baked_food))

200
55.68157235567257
3100.4375


In [53]:
# -1 represent inversely proportional relationship
# 1 represent proportional relationship
# 0 represent no relationship

tobacco_consumption = [30,50,10,30,50,40]
deaths = [100,120,70,100,120,112]

print(np.corrcoef([tobacco_consumption,deaths]))

[[1.         0.99015454]
 [0.99015454 1.        ]]


In [54]:
price = [300,100,350,150,200]
sales = [10,20,7,17,3]

print(np.corrcoef([price,sales]))

[[ 1.         -0.66621445]
 [-0.66621445  1.        ]]
